# Generated by Django 4.0.5 on 2022-06-22 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='liked date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Post created date'),
        ),
    ]
