# Generated by Django 4.0.5 on 2022-06-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_like_datetime_alter_post_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='datetime',
            new_name='created_at',
        ),
    ]
